[package]
name = "function_line_count"
version = "0.1.0"
authors = ["Stefan Lahner <lahner.stefan@gmx.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
